spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 7001 #注册中心占用7001端口,冒号后面必须要有空格
   
spring: 
  profiles: dev
  application:
<<<<<<< HEAD
    name: cloud-config-eureka-client
       
=======
    name: microservicecloud-config-eureka-client
    
>>>>>>> 6746916f293b266d9d28e357037794cc5f8c6d8c
eureka: 
  instance: 
    hostname: eureka7001.com #冒号后面必须要有空格
  client: 
<<<<<<< HEAD
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中1
=======
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
>>>>>>> 6746916f293b266d9d28e357037794cc5f8c6d8c
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
---
server: 
  port: 7001 #注册中心占用7001端口,冒号后面必须要有空格
   
spring: 
  profiles: test
  application:
<<<<<<< HEAD
    name: cloud-config-eureka-client
=======
    name: microservicecloud-config-eureka-client
>>>>>>> 6746916f293b266d9d28e357037794cc5f8c6d8c
    
eureka: 
  instance: 
    hostname: eureka7001.com #冒号后面必须要有空格
  client: 
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/

